language: perl
perl:
   - "5.18"
   - "5.22"
   - "5.24"
   - "5.26"
addons:
  apt:
    packages:
    - dnsutils
install:
  - cpanm Test::More
  - cpanm Data::Dumper
  - cpanm JSON
  - cpanm JSON::Validator
script:
  - prove -v
