language: perl
perl:
   - "5.26"
addons:
  apt:
    packages:
    - dnsutils
    - jsonlint
before_install:
  - if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.pem)|(.pdf)|(.html)|^(LICENSE)|^(docs)|^(utils)|^(bin)|(Dockerfile)'
    then
      echo "no code was updated, not running the CI."
      exit
  fi
install:
  - cpanm --notest Test::More
  - cpanm --notest Data::Dumper
  - cpanm --notest JSON
#  - cpanm JSON::Validator
script:
  - prove -v
